# Generated by Django 6.0 on 2025-12-09 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caricature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='caricatures/', verbose_name='الصورة')),
                ('age_group', models.CharField(max_length=20, verbose_name='الفئة العمرية')),
                ('views', models.IntegerField(default=0, verbose_name='المشاهدات')),
                ('likes', models.IntegerField(default=0, verbose_name='الإعجابات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'كاريكاتير',
                'verbose_name_plural': 'الكاريكاتير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('game_type', models.CharField(choices=[('puzzle', 'ألغاز'), ('memory', 'ذاكرة'), ('educational', 'تعليمية'), ('multiplayer', 'متعددة اللاعبين'), ('quiz', 'اختبار')], max_length=20, verbose_name='نوع اللعبة')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='games/', verbose_name='الصورة المصغرة')),
                ('age_group', models.CharField(max_length=20, verbose_name='الفئة العمرية')),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='easy', max_length=10, verbose_name='المستوى')),
                ('game_url', models.URLField(blank=True, verbose_name='رابط اللعبة')),
                ('game_data', models.JSONField(blank=True, null=True, verbose_name='بيانات اللعبة')),
                ('plays_count', models.IntegerField(default=0, verbose_name='عدد مرات اللعب')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='التقييم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'لعبة',
                'verbose_name_plural': 'الألعاب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='podcasts/', verbose_name='الصورة المصغرة')),
                ('audio_url', models.URLField(verbose_name='رابط الصوت')),
                ('duration', models.IntegerField(default=0, verbose_name='المدة (ثواني)')),
                ('age_group', models.CharField(max_length=20, verbose_name='الفئة العمرية')),
                ('category', models.CharField(max_length=50, verbose_name='الفئة')),
                ('host', models.CharField(blank=True, max_length=100, verbose_name='المقدم')),
                ('plays_count', models.IntegerField(default=0, verbose_name='عدد مرات التشغيل')),
                ('likes', models.IntegerField(default=0, verbose_name='الإعجابات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بودكاست',
                'verbose_name_plural': 'البودكاست',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('summary', models.TextField(max_length=500, verbose_name='الملخص')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='الصورة')),
                ('age_group', models.CharField(max_length=20, verbose_name='الفئة العمرية')),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='easy', max_length=10, verbose_name='المستوى')),
                ('reading_time', models.IntegerField(default=5, verbose_name='وقت القراءة (دقائق)')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='المؤلف')),
                ('views', models.IntegerField(default=0, verbose_name='المشاهدات')),
                ('likes', models.IntegerField(default=0, verbose_name='الإعجابات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قصة',
                'verbose_name_plural': 'القصص',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/', verbose_name='الصورة المصغرة')),
                ('video_url', models.URLField(verbose_name='رابط الفيديو')),
                ('duration', models.IntegerField(default=0, verbose_name='المدة (ثواني)')),
                ('age_group', models.CharField(max_length=20, verbose_name='الفئة العمرية')),
                ('category', models.CharField(max_length=50, verbose_name='الفئة')),
                ('views', models.IntegerField(default=0, verbose_name='المشاهدات')),
                ('likes', models.IntegerField(default=0, verbose_name='الإعجابات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فيديو',
                'verbose_name_plural': 'الفيديوهات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('story', 'قصة'), ('game', 'لعبة'), ('video', 'فيديو'), ('podcast', 'بودكاست'), ('caricature', 'كاريكاتير')], max_length=20, verbose_name='نوع المحتوى')),
                ('content_id', models.IntegerField(verbose_name='معرف المحتوى')),
                ('text', models.TextField(verbose_name='النص')),
                ('is_approved', models.BooleanField(default=True, verbose_name='موافق عليه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content.comment', verbose_name='الرد على')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20, verbose_name='نوع المحتوى')),
                ('content_id', models.IntegerField(verbose_name='معرف المحتوى')),
                ('progress', models.IntegerField(default=0, verbose_name='التقدم %')),
                ('completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('score', models.IntegerField(blank=True, default=0, null=True, verbose_name='النقاط')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='آخر وصول')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقدم المستخدم',
                'verbose_name_plural': 'تقدم المستخدمين',
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
    ]
