# Generated by Django 5.2.12 on 2026-05-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('image', models.ImageField(blank=True, null=True, upload_to='parent_tips/', verbose_name='الصورة')),
                ('category', models.CharField(choices=[('protection', 'حماية الأطفال من المحتوى غير المناسب'), ('screen_time', 'تنظيم وقت الشاشة'), ('digital_edu', 'التربية الرقمية'), ('online_safety', 'الأمان على الإنترنت')], max_length=50, verbose_name='الفئة')),
                ('content_preparation', models.CharField(blank=True, max_length=200, verbose_name='إعداد المحتوى')),
                ('execution', models.CharField(blank=True, max_length=200, verbose_name='تنفيذ')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نصيحة لولي الأمر',
                'verbose_name_plural': 'نصائح أولياء الأمور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='caricature',
            name='content_preparation',
            field=models.CharField(blank=True, max_length=200, verbose_name='إعداد المحتوى'),
        ),
        migrations.AddField(
            model_name='caricature',
            name='execution',
            field=models.CharField(blank=True, max_length=200, verbose_name='تنفيذ'),
        ),
        migrations.AddField(
            model_name='game',
            name='content_preparation',
            field=models.CharField(blank=True, max_length=200, verbose_name='إعداد المحتوى'),
        ),
        migrations.AddField(
            model_name='game',
            name='execution',
            field=models.CharField(blank=True, max_length=200, verbose_name='تنفيذ'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='content_preparation',
            field=models.CharField(blank=True, max_length=200, verbose_name='إعداد المحتوى'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='execution',
            field=models.CharField(blank=True, max_length=200, verbose_name='تنفيذ'),
        ),
        migrations.AddField(
            model_name='story',
            name='content_preparation',
            field=models.CharField(blank=True, max_length=200, verbose_name='إعداد المحتوى'),
        ),
        migrations.AddField(
            model_name='story',
            name='execution',
            field=models.CharField(blank=True, max_length=200, verbose_name='تنفيذ'),
        ),
        migrations.AddField(
            model_name='video',
            name='content_preparation',
            field=models.CharField(blank=True, max_length=200, verbose_name='إعداد المحتوى'),
        ),
        migrations.AddField(
            model_name='video',
            name='execution',
            field=models.CharField(blank=True, max_length=200, verbose_name='تنفيذ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.CharField(choices=[('story', 'قصة'), ('game', 'لعبة'), ('video', 'فيديو'), ('podcast', 'بودكاست'), ('caricature', 'كاريكاتير'), ('parent_tip', 'نصيحة لولي الأمر')], max_length=20, verbose_name='نوع المحتوى'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('awareness', 'فيديوهات توعوية'), ('activities', 'أنشطة وتحديات'), ('quick_info', 'معلومات سريعة')], max_length=50, verbose_name='الفئة'),
        ),
    ]
