# Generated by Django 5.2.12 on 2026-05-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_parenttip_caricature_content_preparation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='وصف قصير')),
                ('image', models.ImageField(upload_to='infographics/', verbose_name='الصورة')),
                ('category', models.CharField(choices=[('digital_awareness', 'توعية رقمية'), ('positive_behavior', 'سلوكيات إيجابية'), ('online_safety', 'الأمان على الإنترنت'), ('health_habits', 'الصحة والعادات'), ('quick_info', 'معلومات سريعة')], max_length=50, verbose_name='التصنيف')),
                ('age_group', models.CharField(max_length=20, verbose_name='الفئة العمرية')),
                ('content_preparation', models.CharField(blank=True, max_length=200, verbose_name='إعداد المحتوى')),
                ('execution', models.CharField(blank=True, max_length=200, verbose_name='تنفيذ')),
                ('views', models.IntegerField(default=0, verbose_name='المشاهدات')),
                ('likes', models.IntegerField(default=0, verbose_name='الإعجابات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إنفوجرافيك',
                'verbose_name_plural': 'الإنفوجرافيك',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.CharField(choices=[('story', 'قصة'), ('game', 'لعبة'), ('video', 'فيديو'), ('podcast', 'بودكاست'), ('caricature', 'كاريكاتير'), ('parent_tip', 'نصيحة لولي الأمر'), ('infographic', 'إنفوجرافيك')], max_length=20, verbose_name='نوع المحتوى'),
        ),
    ]
