# Generated by Django 5.2.12 on 2026-05-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_infographic_alter_comment_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='رابط الصورة (اختياري)'),
        ),
    ]
