# Generated by Django 5.2.12 on 2026-05-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_story_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='daily_tip',
            field=models.TextField(blank=True, verbose_name='نصيحة اليوم'),
        ),
        migrations.AddField(
            model_name='story',
            name='goal',
            field=models.TextField(blank=True, verbose_name='هدف القصة'),
        ),
    ]
