# Generated by Django 5.2.12 on 2026-05-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_story_daily_tip_story_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='daily_tip',
            field=models.TextField(blank=True, default='', verbose_name='نصيحة اليوم'),
        ),
        migrations.AlterField(
            model_name='story',
            name='goal',
            field=models.TextField(blank=True, default='', verbose_name='هدف القصة'),
        ),
    ]
