# Generated by Django 5.2.12 on 2026-05-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_story_daily_tip_alter_story_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('awareness', 'فيديوهات توعوية'), ('activities', 'أنشطة وتحديات'), ('quick_info', 'معلومات سريعة'), ('reports', 'تقارير ميدانية')], max_length=50, verbose_name='الفئة'),
        ),
    ]
