# Generated by Django 5.2.12 on 2026-05-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, verbose_name='رابط الصورة المصغرة (اختياري)'),
        ),
    ]
