# Generated by Django 5.2.12 on 2026-05-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_video_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('summary', models.TextField(max_length=500, verbose_name='الملخص')),
                ('cover_image_url', models.URLField(blank=True, verbose_name='رابط صورة الغلاف')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='اسم الكاتب')),
                ('content_blocks', models.JSONField(default=list, verbose_name='محتوى المقال (Blocks)')),
                ('category', models.CharField(choices=[('awareness', 'مقال توعوي'), ('visual', 'مقال مصور'), ('tips', 'نصائح رقمية'), ('health', 'صحة رقمية'), ('safety', 'أمان رقمي')], max_length=50, verbose_name='الفئة')),
                ('age_group', models.CharField(max_length=20, verbose_name='الفئة العمرية')),
                ('reading_time', models.IntegerField(default=5, verbose_name='مدة القراءة (دقائق)')),
                ('content_preparation', models.CharField(blank=True, max_length=200, verbose_name='إعداد المحتوى')),
                ('execution', models.CharField(blank=True, max_length=200, verbose_name='تنفيذ')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-published_at'],
            },
        ),
    ]
