# Generated by Django 5.2.12 on 2026-05-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Podcast',
        ),
        migrations.AddField(
            model_name='infographic',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='الكاتب'),
        ),
        migrations.AddField(
            model_name='infographic',
            name='content',
            field=models.TextField(blank=True, verbose_name='المحتوى'),
        ),
        migrations.AddField(
            model_name='infographic',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='رابط الصورة الرئيسية'),
        ),
        migrations.AddField(
            model_name='parenttip',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='الكاتب'),
        ),
        migrations.AddField(
            model_name='parenttip',
            name='cover_image_url',
            field=models.URLField(blank=True, verbose_name='رابط صورة الغلاف'),
        ),
        migrations.AddField(
            model_name='parenttip',
            name='summary',
            field=models.TextField(blank=True, verbose_name='وصف قصير'),
        ),
        migrations.AlterField(
            model_name='infographic',
            name='age_group',
            field=models.CharField(default='8-12', max_length=20, verbose_name='الفئة العمرية'),
        ),
        migrations.AlterField(
            model_name='infographic',
            name='category',
            field=models.CharField(choices=[('online_safety', 'الأمان الإلكتروني'), ('digital_health', 'الصحة الرقمية'), ('digital_awareness', 'التوعية الرقمية'), ('cyberbullying', 'التنمر الإلكتروني'), ('privacy', 'الخصوصية'), ('safe_internet', 'الاستخدام الآمن للإنترنت')], max_length=50, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='infographic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='infographics/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='parenttip',
            name='category',
            field=models.CharField(choices=[('screen_time', 'تنظيم وقت الشاشة'), ('sleep', 'النوم والشاشات'), ('games', 'الألعاب الإلكترونية'), ('protection', 'حماية الأطفال'), ('mental_health', 'الصحة النفسية'), ('family_comms', 'التواصل الأسري')], max_length=50, verbose_name='الفئة'),
        ),
    ]
