# Generated by Django 5.2.12 on 2026-05-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_delete_podcast_infographic_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creators',
            field=models.CharField(blank=True, max_length=255, verbose_name='منفذو اللعبة / الإعداد'),
        ),
        migrations.AddField(
            model_name='game',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='وصف قصير'),
        ),
        migrations.AddField(
            model_name='game',
            name='thumbnail_url',
            field=models.URLField(blank=True, verbose_name='رابط الصورة المصغرة الخارجية'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('educational', 'ألعاب تعليمية'), ('intelligence', 'ألعاب ذكاء'), ('digital_safety', 'ألعاب أمان رقمي'), ('focus', 'ألعاب تركيز'), ('purposeful_fun', 'ألعاب ترفيهية هادفة')], max_length=20, verbose_name='نوع اللعبة'),
        ),
    ]
